### PR TITLE
Design overhaul v2

### PR DESCRIPTION
**Pull request by aleksandra-tedeeva**

### CODE REVIEW

**Comment by xWektx** [comment]
94cMKxBHWSY
BOlPlvmSlic

**Comment by xWektx** [comment]
The mobile version does not include "Help Information".
image

**Comment by xWektx** [comment]
image
image

In mobile versions, the search is partially cut.

**Comment by xWektx** [comment]
image


Since our site is Russian, the user will most likely try to enter “M” and “B” in Russian and find that the search does not work as a result.

**Comment by xWektx** [comment]
image
image

image
image

It is not very convenient to understand what the values are measured in. The unit of measurement is too far away.
It looks better on the mobile version because the values are closer, but when moving down you can lose what it refers to.

**Comment by aleksandra-tedeeva** [comment]
@xWektx, thank you for the good review, I will fix these issues

**Pull request merged**
